/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTelementryRouteImport } from './routes/dashboard.telementry'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSensorsRouteImport } from './routes/dashboard.sensors'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardControlRouteImport } from './routes/dashboard.control'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTelementryRoute = DashboardTelementryRouteImport.update({
  id: '/telementry',
  path: '/telementry',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSensorsRoute = DashboardSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardControlRoute = DashboardControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/control': typeof DashboardControlRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/telementry': typeof DashboardTelementryRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/control': typeof DashboardControlRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/telementry': typeof DashboardTelementryRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/control': typeof DashboardControlRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/telementry': typeof DashboardTelementryRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/control'
    | '/dashboard/logs'
    | '/dashboard/sensors'
    | '/dashboard/settings'
    | '/dashboard/telementry'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/control'
    | '/dashboard/logs'
    | '/dashboard/sensors'
    | '/dashboard/settings'
    | '/dashboard/telementry'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/control'
    | '/dashboard/logs'
    | '/dashboard/sensors'
    | '/dashboard/settings'
    | '/dashboard/telementry'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telementry': {
      id: '/dashboard/telementry'
      path: '/telementry'
      fullPath: '/dashboard/telementry'
      preLoaderRoute: typeof DashboardTelementryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sensors': {
      id: '/dashboard/sensors'
      path: '/sensors'
      fullPath: '/dashboard/sensors'
      preLoaderRoute: typeof DashboardSensorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/control': {
      id: '/dashboard/control'
      path: '/control'
      fullPath: '/dashboard/control'
      preLoaderRoute: typeof DashboardControlRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardControlRoute: typeof DashboardControlRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardSensorsRoute: typeof DashboardSensorsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTelementryRoute: typeof DashboardTelementryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardControlRoute: DashboardControlRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardSensorsRoute: DashboardSensorsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTelementryRoute: DashboardTelementryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
